services:
  postgres:
    container_name: book_social_network_db
    image: postgres:16.2
    environment:
      POSTGRES_DB: book_social_network
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: amazigh
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/data/postgres
    networks:
      - spring-app
    ports:
      - 5432:5432
    restart: unless-stopped

  bsn-api:
    container_name: bsn-api
    image: bsn/bsn:1.0.2
    ports:
      - 8080:8080
    networks:
      - spring-app
    depends_on:
      - postgres

  bsn-ui:
    container_name: bsn-ui
    image: bsn/bsn-ui:1.0.0
    ports:
      - 4200:80
    networks:
      - spring-app
    depends_on:
      - bsn-api

  # mail-dev:
  #   container_name: mail_dev
  #   image: maildev/maildev
  #   ports:
  #     - 1080:1080
  #     - 1025:1025
  #   restart: unless-stopped
  #   networks:
  #     - spring-app

volumes:
  postgres:
    driver: local

networks:
  spring-app:
    driver: bridge
